container_name       = "introduction-to-terraform"
key                  = "raffaele/terraform.tfstate"
storage_account_name = "introductiontoterraform"
access_key           = ""
metadata_host        = "management.azure.com"